workflows:
  ios_build:
    name: "Karzararv3 iOS Build"
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: "stable"
      xcode: "latest"
      vars:
        APP_BUNDLE_ID: "com.example.karzararv3"
    scripts:
      - name: "Install dependencies"
        script: "flutter pub get"
      - name: "Build iOS IPA"
        script: "flutter build ipa --release"
    artifacts:
      - "build/ios/ipa/*.ipa"
