workflows:
  ios_build:
    name: Karzararv2 iOS Build
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_BUNDLE_ID:"com.example.karzararv3"
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS Release (No Codesign)
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa
